"""
This file consists of a handler function which is unique to each websocket "task". The client ID
is generated by each client and has been initialised to None. 

I have also used rate limiting per client in case this has to be scaled up. Rate limiter
can be configured based on how many reqs are allowed per second. This enhancement has only been 
made keeping in mind that multiple clients can be connected to this server. 
"""

import asyncio
from websockets.exceptions import ConnectionClosed
import json
import logging
from message_creator import MessageCreator
from status_codes import StatusCode

logger = logging.getLogger(__name__)

async def connection_handler(websocket, limiter):
    client_id = None
    message_creator = MessageCreator()
    try:
        async for message in websocket:
            try:
                message_body = json.loads(message)

                ## The client has been designed to send an init message 
                ## with client id that has been generated on client side, as soon
                # as the connection is established.
                 
                if client_id is None:
                    if "client_id" not in message_body:
                        await websocket.send(json.dumps({"status_code": StatusCode.BAD_REQUEST.value, "error": "client_id required"}))
                        continue
                    client_id = message_body["client_id"]
                    logger.info(f"[Client {client_id}] Connected")
                    continue

                ## RATE LIMITER LOGIC: although I know this is a websocket server, I rate limited because
                ## we do not want too many calls to the LLM from a single client. I have implemented this
                # purely as a "good-to-have" feature 
                if not await limiter.allow(client_id):
                    logger.warning(f"[Client {client_id}] : Rate limit exceeded for client")
                    await websocket.send(
                        json.dumps({"status_code": StatusCode.RATE_LIMITED.value, "error": f"Rate limit exceeded for client: {client_id}"})
                    )
                    # Skip processing this message but keep connection open
                    continue

                ## this will basically be the message body that we will get text grom and then
                ## send to our llm. 
                if "data" not in message_body or not isinstance(message_body["data"], str):
                    await websocket.send(
                        json.dumps({"status_code": StatusCode.BAD_REQUEST.value, "error": "Invalid payload: 'data' must be a string"})
                    )
                    continue

                data = message_body['data']
                logger.info("Creating response...")
                response = await message_creator.create_message(data)
                logger.debug(f"Response: \n\n{response}\n\n")
                await websocket.send(
                    response
                )

                logger.info(f"[Client {client_id}] : Response generated and transmitted")

            except json.JSONDecodeError:
                logger.error(f"[Client {client_id}] : JSON decode error from client: {message}")
                logger.debug(f"Client (raw): {message}")
                await websocket.send(
                    json.dumps({"status_code": StatusCode.BAD_REQUEST, "error": "unexpected data format"})
                )
            except Exception as e:
                logger.error(f"[Client {client_id}] : Unexpected error processing message from client: {e}")
                # I will not close the connection, but I will continue listening for next messages
            except asyncio.CancelledError:
                logger.info(f"[Client {client_id}] Task cancelled")
                raise

    except ConnectionClosed:
        logger.info(f"[Client {client_id}] : Client disconnected")
